### ISSUE TITLE
how to run testcases in serial, not in parallel by testr?

### ISSUE THREAD

**Issue by zhangzx7054** [testing-cabal/testrepository#31]
I'd like to run testcases in serial, but I don't know how to configure tox's settings, and don't get any answer by google.

I have read [http://testrepository.readthedocs.io/en/latest/MANUAL.html#parallel-testing](url) , and know the command `"testr run --parallel"`. Although in my script. there is no options `"--parallel`, the testcases run in parallel actually. So I'm confused.

In my script,  the command is " bash -c "TESTS_DIR=./tests/ python setup.py testr --slowest --testr-args='{posargs}'""

**Comment by mtreinish** [comment]
Your tox.ini isn't running testr, you're using the pbr wrapper for testr: https://docs.openstack.org/pbr/latest/user/using.html#testing PBR is calling testr there. By default PBR calls testr in parallel, if you want to run tests serially using pbr's testr module use the test command's "--no-parallel" flag.

**Comment by zhangzx7054** [comment]
Thank you very much.
