### ISSUE TITLE
db type could not be determined

### ISSUE THREAD

**Issue by ssbarnea** [testing-cabal/testrepository#33]
It seems that if py27 is run before py3x the database format is not recognised anymore.

This bug affects lots of project in the wild and some of them are going for ugly workarounds for avoiding this bug:
* https://bugs.launchpad.net/testrepository/+bug/1229445
* https://ask.openstack.org/en/question/5310/db-type-could-not-be-determined/

**Comment by rbtcollins** [comment]
With python 2 behind us, I'm going to close this bug: the extra db type it supported is no longer relevant - while we could in principle write a converter, it would have be written in Python2, or be a C extension model to Python. The data that would be lost is just timing data.
