### ISSUE TITLE
RFE: use `zoneinfo` instead of `pytz`

### ISSUE THREAD

**Issue by kloczek** [testing-cabal/testrepository#56]
Switch to standard `zoneinfo` module.
Below may help  https://github.com/pydantic/pydantic-core/commit/fd262933

**Comment by rbtcollins** [comment]
Whats the motivation?

**Comment by cjwatson** [comment]
I think there's something to be said for avoiding non-stdlib dependencies when they're not needed.  pytz used to be one of the easiest ways to get hold of a timezone object, but that hasn't been the case for a while now.

That said, I don't know why this package would use `zoneinfo`, since (unlike pydantic-core) it only uses `pytz.UTC`.  `datetime.timezone.utc` is simpler and should be good enough.

**Comment by rbtcollins** [comment]
`zoneinfo` was introduced in 3.11; 3.8 is still receiving security fixes; I'm not super keen with Python with depending on the latest and greatest - have had significant pain with slow upgraders in the past.

https://docs.python.org/3/library/datetime.html#datetime.timezone.utc sadly doesn't list when it was added; possibly 3.2.

**Comment by cjwatson** [comment]
It was indeed [added](https://github.com/python/cpython/commit/4e749a1113acb4affed27afda07e17d96945290b) in Python 3.2.  That would require testrepository dropping support for Python 2 (which I assume only hasn't been done because nobody has got round to it yet, but can you confirm that?).

**Comment by rbtcollins** [comment]
I think its dropped in every way that matters. We can remove the classifier as well of course.

**Comment by kloczek** [comment]
Additionally `zoneinfo` has been introduced in python 3.9 https://docs.python.org/3/library/zoneinfo.html
Python 3.8 will be EOSed in few weeks (Oct this year).

**Comment by cjwatson** [comment]
This is true, but it's moot since there's absolutely no point in using zoneinfo for UTC.  It's only needed when you need other timezones from the IANA database.

**Comment by kloczek** [comment]
Both modules ze in standard OOTB set.
If you have any idea how to measure reading UTC time over `zoneinfo`  or `datetime`  metrics values taken from such reads should be used to make final decision.

**Comment by cjwatson** [comment]
Even the `zoneinfo` docs mention using `timezone.utc` for the UTC case.

**Comment by cjwatson** [comment]
#64 drops Python 2 support.  If that looks good then we can take advantage of py3-specific timezone handling after that.
